server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;

        # Allow frontend (e.g., http://localhost:4200) to access this server
        add_header 'Access-Control-Allow-Origin' '*' always;

        # Allow Content-Disposition to be accessed by client JS
        add_header 'Access-Control-Expose-Headers' 'Content-Disposition' always;
    }
}
